### ISSUE TITLE
Error in test.py

### ISSUE THREAD

**Issue by maybeLx** [vkvats/GC-MVSNet#1]
nice work, but I find there is no folder named "filter" in test.py

**Comment by maybeLx** [comment]
Also I find load the pre-trained ckpt failed due to the mismatch of ckpt and model . 
<img width="1215" alt="image" src="https://github.com/vkvats/GC-MVSNet/assets/108978824/0e662777-b5c5-4a57-9e87-c1e453c6728b">

**Comment by Gwencong** [comment]
I encountered the same problem, and then I checked the Google link of the pretrained model provided in this repository. The provided link is the pretrained model link of [TransMVSNet](https://github.com/megvii-research/TransMVSNet), so the code cannot run. It seems that the author forgot to make changes.

**Comment by vkvats** [comment]
Thank you for point it out, you are right @Gwencong, I forgot to point to the new pre-trained model, it's been fixed now. 

Hope this helps.

**Comment by vkvats** [comment]
> nice work, but I find there is no folder named "filter" in test.py

The 'filter' part is not needed for GC-MVSNet, you can comment that out if you find it anywhere. I have removed it from test.py. That was for next set of experiments that I was doing and is not relevant to GC-MVSNet. 

Hope it helps!

**Comment by maybeLx** [comment]
Thanks

**Comment by maybeLx** [comment]
> Thank you for point it out, you are right @Gwencong, I forgot to point to the new pre-trained model, it's been fixed now.
> 
> Hope this helps.

I noticed that there is only a checkpoint trained on DTU. Have you uploaded model fine-tuning on BlendedMVS ?
